### ISSUE TITLE
Game crashing when walking away after setting Planewalk

### ISSUE THREAD

**Issue by HyScript7** [stormdirus2/the-planeswalker#3]
The game crashes after I use Planewalk (Shift + Primary Ability) and walk away from the place where I set it.
I took what seemed related from the logs:
```
[23:25:59] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[23:25:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:25:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:25:59] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:25:59] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:25:59] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:25:59] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Apoli, Fabric Tool Attribute API (v1), Origins, Origins: The Planeswalker)
[23:25:59] [Worker-Main-3/INFO]: Loaded 7 recipes
[23:26:00] [Worker-Main-3/INFO]: Loaded 1139 advancements
[23:26:00] [Worker-Main-3/ERROR]: There was a problem reading sub-power "theplaneswalker:planewalk_void" in power file "theplaneswalker:planewalk": Cannot read field "field_6002" because "entity" is null
[23:26:00] [Worker-Main-3/INFO]: Finished loading powers from data files. Registry contains 124 powers.
[23:26:00] [Worker-Main-3/INFO]: Finished loading origins from data files. Registry contains 12 origins.
[23:26:00] [Worker-Main-3/INFO]: Trying to read layer file: origins:origin
[23:26:00] [Worker-Main-3/INFO]: Trying to read layer file: origins:origin
[23:26:00] [Worker-Main-3/INFO]: Finished loading origin layers from data files. Read 1 layers.
```

```
[23:26:33] [User Authenticator #1/INFO]: UUID of player HyScript7 is 5e995427-c2f3-45b4-860c-08405da9de1b
[23:26:33] [Server thread/INFO]: HyScript7[/**.**.**.**:42074] logged in with entity id 402 at (187.5, 71.0, -36.5)
[23:26:33] [Server thread/WARN]: Player class_3222['HyScript7'/402, l='ServerLevel[world]', x=187.50, y=71.00, z=-36.50] could not be synced because server networking isn't set up yet.
[23:26:33] [Server thread/INFO]: HyScript7 joined the game
[23:26:40] [Server thread/INFO]: Player HyScript7 chose Origin: theplaneswalker:planeswalker, for layer: origins:origin
[23:26:55] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:895) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.scirave.theplaneswalker.origins.DimensionPower.updateWorld(net.minecraft.class_3218)" because "power" is null
at net.scirave.theplaneswalker.origins.TCEntityActions.lambda$initialization$0(TCEntityActions.java:51) ~[The+Planeswalker+-+2.0.1.jar:?]
at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) ~[8a3d65cb-7287-4f24-9dc9-8b29616228e4.jar:?]
at io.github.apace100.apoli.power.ResourcePower.setValue(ResourcePower.java:30) ~[8a3d65cb-7287-4f24-9dc9-8b29616228e4.jar:?]
at net.scirave.theplaneswalker.origins.TCEntityActions.lambda$initialization$2(TCEntityActions.java:93) ~[The+Planeswalker+-+2.0.1.jar:?]
at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) ~[8a3d65cb-7287-4f24-9dc9-8b29616228e4.jar:?]
at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:35) ~[8a3d65cb-7287-4f24-9dc9-8b29616228e4.jar:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:169) ~[8a3d65cb-7287-4f24-9dc9-8b29616228e4.jar:?]
at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source) ~[?:?]
at net.minecraft.class_3218.handler$zim000$tick(class_3218.java:2577) ~[intermediary-server.jar:?]
at net.minecraft.class_3218.method_18762(class_3218.java:655) ~[intermediary-server.jar:?]
at net.minecraft.class_1937.method_18472(class_1937.java:483) ~[intermediary-server.jar:?]
at net.minecraft.class_3218.method_31420(class_3218.java:417) ~[intermediary-server.jar:?]
at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[intermediary-server.jar:?]
at net.minecraft.class_3218.method_18765(class_3218.java:392) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[intermediary-server.jar:?]
... 5 more
```
I am running the latest version on latest Fabric 1.17.1 on Java 16
I was testing on a server, successfully recreated this bug twice
No mods other than Origins and The Planes Walker were present.

How to recreate:
1) Create a new world & choose planeswalker as the origin
2) Use Shift + Primary, and walk away until the progress bar that apeared is full.
3) Game should've crashed

**Comment by HyScript7** [comment]
Figured I should probably include the server crash log:
```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/1/21, 11:26 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.scirave.theplaneswalker.origins.DimensionPower.updateWorld(net.minecraft.class_3218)" because "power" is null
	at net.scirave.theplaneswalker.origins.TCEntityActions.lambda$initialization$0(TCEntityActions.java:51)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ResourcePower.setValue(ResourcePower.java:30)
	at net.scirave.theplaneswalker.origins.TCEntityActions.lambda$initialization$2(TCEntityActions.java:93)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:35)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:169)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zim000$tick(class_3218.java:2577)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.scirave.theplaneswalker.origins.TCEntityActions.lambda$initialization$0(TCEntityActions.java:51)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ResourcePower.setValue(ResourcePower.java:30)
	at net.scirave.theplaneswalker.origins.TCEntityActions.lambda$initialization$2(TCEntityActions.java:93)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:35)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:169)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zim000$tick(class_3218.java:2577)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 402
	Entity Name: HyScript7
	Entity's Exact location: 227.29, 70.02, 12.02
	Entity's Block location: World: (227,70,12), Section: (at 3,6,12 in 14,4,0; chunk contains blocks 224,0,0 to 239,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.10, -0.15, 0.08
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)

-- Affected level --
Details:
	All players: 1 total; [class_3222['HyScript7'/402, l='ServerLevel[world]', x=227.29, y=70.02, z=12.02]]
	Chunk stats: 2201
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,70,-32), Section: (at 0,6,0 in 12,4,-2; chunk contains blocks 192,0,-32 to 207,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 786 game time, 786 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 140424 (now: false), thunder time: 65539 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-77-generic
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1041135664 bytes (992 MiB) / 2902458368 bytes (2768 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7F72 24-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 48
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129834.34
	Virtual memory used (MB): 78960.13
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 689.98
	JVM Flags: 2 total; -Xmx3072M -Xms1536M
	Fabric Mods: 
		apoli: Apoli 2.0.0
		calio: Calio 1.0.3
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.7
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		origins: Origins 1.1.0
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		theplaneswalker: Origins: The Planeswalker unspecified
	Player Count: 1 / 20; [class_3222['HyScript7'/402, l='ServerLevel[world]', x=227.29, y=70.02, z=12.02]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```
